app:
    resource: "@AppBundle/Controller/"
    type:     annotation

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /login

facebook_check:
    pattern: /login/check-facebook

facebook_login:
    pattern: /connect/facebook

google_check:
    pattern: /login/check-google

google_login:
    pattern: /connect/google

formLogin_check:
    path: /login_check

logout:
    path: /logout