security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
        AppBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        user_db_provider:
            entity:
                class: AppBundle:User
                property: email
        oauth_provider:
            id: oauth_test_provider

    firewalls:
        main:
            pattern:    ^/

            form_login:
                provider: user_db_provider
                login_path: /login
                check_path: /login_check
                default_target_path: secured_zone
                username_parameter: _username
                password_parameter: _password
            logout: true
            anonymous: ~
            switch_user: true

            oauth:
                resource_owners:
                    facebook: "/login/check-facebook"
                    google: "/login/check-google"
                login_path: /
                use_forward: false
                failure_path: /
                oauth_user_provider:
                    service: oauth_test_provider

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/secure, role: ROLE_USER }


